# Generated by Django 5.2.17 on 2026-08-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfectDay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='forumpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorid', models.SmallIntegerField()),
                ('author', models.CharField()),
                ('questionid', models.SmallIntegerField()),
                ('text', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='forumquestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorid', models.SmallIntegerField()),
                ('author', models.CharField()),
                ('text', models.CharField()),
            ],
        ),
    ]
