# Generated by Django 5.2.17 on 2026-08-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfectDay', '0002_forumpost_forumquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='forumquestion',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='questionid',
        ),
    ]
