# Generated by Django 5.2.17 on 2026-08-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfectDay', '0003_delete_forumquestion_remove_forumpost_questionid'),
    ]

    operations = [
        migrations.CreateModel(
            name='todotask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorid', models.SmallIntegerField()),
                ('text', models.CharField()),
                ('done', models.BooleanField(default=False)),
                ('due', models.DateTimeField()),
            ],
        ),
    ]
