# Generated by Django 5.2.17 on 2026-08-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfectDay', '0004_todotask'),
    ]

    operations = [
        migrations.CreateModel(
            name='journalentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorid', models.SmallIntegerField()),
                ('text', models.CharField()),
                ('rating', models.CharField()),
            ],
        ),
    ]
