# Generated by Django 5.2.17 on 2026-08-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfectDay', '0005_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='event',
            field=models.CharField(default='i had fun'),
            preserve_default=False,
        ),
    ]
