# Generated by Django 5.2.17 on 2026-09-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfectDay', '0006_journalentry_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='due',
            field=models.DateField(),
        ),
    ]
